services:

    OxidSupport\Logger\Logger\ShopLoggerInterface:
        class: OxidSupport\Logger\Logger\ShopLogger
        autowire: true
        public: true

    OxidSupport\Logger\Request\CorrelationIdProviderInterface:
        class: OxidSupport\Logger\Request\CorrelationIdProvider

    oxs.logger.request:
        class: Monolog\Logger
        factory: ['OxidSupport\Logger\Logger\LoggerFactory', 'create']
        arguments:
            - '@OxidSupport\Logger\Request\CorrelationIdProviderInterface'
        public: true

    OxidSupport\Logger\Logger\ShopLoggerFactory:
        factory: ['OxidSupport\Logger\Logger\ShopLoggerFactory', 'create']
        arguments:
            - '@OxidSupport\Logger\Logger\ShopLoggerInterface'
        public: true
