services:

    _defaults:
        autowire: true
        public: false

    OxidSupport\Logger\Logger\ShopLoggerInterface:
        class: OxidSupport\Logger\Logger\ShopLogger

    OxidSupport\Logger\Request\CorrelationIdProviderInterface:
        class: OxidSupport\Logger\Request\CorrelationIdProvider

    oxs.logger.request:
        class: Monolog\Logger
        factory: ['OxidSupport\Logger\Logger\LoggerFactory', 'create']
        arguments:
            - '@OxidSupport\Logger\Request\CorrelationIdProviderInterface'
        public: true
        autowire: false

    OxidSupport\Logger\Logger\ShopLoggerFactory:
        factory: ['OxidSupport\Logger\Logger\ShopLoggerFactory', 'create']
        arguments:
            - '@OxidSupport\Logger\Logger\ShopLoggerInterface'
        public: true
        autowire: false
